require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'spec/factories/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - Guardfile
  DisplayCopNames: true

Metrics/LineLength:
  Max: 118

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

