require: rubocop-rspec

AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'spec/factories/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - Guardfile
    - Gemfile
  DisplayCopNames: true

Metrics/AbcSize:
  Exclude:
    - app/models/ability.rb

Metrics/MethodLength:
  Exclude:
    - app/models/ability.rb

Metrics/LineLength:
  Max: 98

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

# "The first argument to describe should be the class or module being tested"
# NOT for spec/api
RSpec/DescribeClass:
  Enabled: false
