require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'spec/factories/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - Guardfile
    - Gemfile
  DisplayCopNames: true

Metrics/LineLength:
  Max: 98

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false
